#!/bin/bash 

. config

# 1. Install tinc on all nodes + upload service file + enable tinc.service [DONE]
# 2. Create /etc/tinc/NETWORK/tinc.conf,hosts(empty folder) - Define NETWORK (own name + tun name)
# 3. Create host config file
# 4. Generate N host deinccfinitions (keys) and exchange keys
# 5. start tinc service on all hosts

./01-tinc-installation
./02-tinc-host-file-config
./03-tinc-up-down-config
./04-tinc-key-gen-exchange
./05-tinc-start
