#!/bin/bash


##########################

# Stop tinc and remove tinc from all nodes.

##########################

. config

PUBLIC_IPS=$(cat ${PUBLIC_IPS_FILE})

ALL_DESTINATIONS=$(./hosts2dests.sh "${PUBLIC_IPS}" ${VM_USERNAME})
echo ${ALL_DESTINATIONS}


# Step 1: Start tinc all nodes

echo -e "\e[44mREMOVE TINC ON NODES: ${ALL_DESTINATIONS}\e[0m"

IFS=","
for DESTINATION in ${ALL_DESTINATIONS}
do
  SSH_HOST=${DESTINATION%:*}
  rm ~/.ssh/known_hosts >/dev/null 2>&1

  ssh -o StrictHostKeyChecking=no -i ${SSH_KEY_FILE} ${SSH_HOST}  "sudo tinc -n ${VPN_NAME} stop; sudo rm -r /etc/tinc/${VPN_NAME}"
done
unset IFS



































