#!/bin/bash
echo Bandwidths
./03-show-current-bandwidth-latency-state.sh | sed 's/\"//g' | sed 's/,/ /g' | sed 's/dst-network=//g' | sed 's#/32  protocol=ip# #g' | sed 's/}//g' | sed 's/{//g' | sed 's/://g' | sed 's/rate//g' | sed 's/delay//g' | sed 's/[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*//g' | sed 's/[0-9]*ms//g' | sed 's/Mbps/,/g'
echo Latenicies
./03-show-current-bandwidth-latency-state.sh | sed 's/\"//g' | sed 's/,/ /g' | sed 's/dst-network=//g' | sed 's#/32  protocol=ip# #g' | sed 's/}//g' | sed 's/{//g' | sed 's/://g' | sed 's/rate//g' | sed 's/delay//g' | sed 's/[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*//g' | sed 's/[0-9]*Mbps//g' | sed 's/ms/,/g'

